/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.niraj.simplewindow.views;

import com.niraj.simplewindow.controller.BusinessLogic;
import com.niraj.simplewindow.entity.Account;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ListAllAccounts extends javax.swing.JInternalFrame {
    
    int row;
    BusinessLogic bl;
    DefaultTableModel dtm;
    ArrayList<Account> aList;
    javax.swing.JFrame callerFrame;
    
    /** Creates new form ListAllAccounts */
    public ListAllAccounts() {
        this.dtm = new DefaultTableModel();
        initComponents();
        row = -1;
        
    }
    
    public ListAllAccounts(BusinessLogic bl, javax.swing.JFrame frame) {
        this.callerFrame = frame;
        this.dtm = new DefaultTableModel();
        initComponents();
        this.bl = bl;
        this.dtm = (DefaultTableModel) tblAccounts.getModel();
        this.initialLoadTable();
        row = -1;
    }
    
    
    public void initialLoadTable(){
        aList = bl.listAll();
        for(Account a: aList){
            Object[] data = {a.getAccNo(), a.getName(), a.getAddress(), a.getAmount(), a.getAccType()=='S'?"Savings":a.getAccType()=='C'?"Current":"Fixed"};
            dtm.addRow(data);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("List of All Accounts");
        setToolTipText("");

        jLabel1.setText("Accounts List : ");

        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No", "Account Holder's Name", "Address", "Amount", "Account Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAccounts);

        jButton1.setText("Deposit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountsMouseClicked
        // TODO add your handling code here:
        //row = Integer.parseInt(tblAccounts.getValueAt(tblAccounts.getSelectedRow(), 0).toString());
//        row = Integer.parseInt(tblAccounts.getValueAt(tblAccounts.getSelectedRow(), 0).toString());
          int selectedRow = tblAccounts.getSelectedRow();
          String value = tblAccounts.getValueAt(selectedRow, 0).toString();
          row = Integer.parseInt(value);
          
          
        
        //System.out.println("Accountnumber of selected item: "+row);
        //System.out.println(row);
    }//GEN-LAST:event_tblAccountsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Please select an account to deposit.", "Selection Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Deposit dp = new Deposit(bl, row);
        callerFrame.add(dp);
        dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblAccounts;
    // End of variables declaration//GEN-END:variables

}
